// for site datas
export const APP_LANGUAGE_CHANGE_SUCCESS 		= 'APP_LANGUAGE_CHANGE_SUCCESS';
export const APP_CURRENCY_CHANGE_SUCCESS 		= 'APP_CURRENCY_CHANGE_SUCCESS';


export const GET_SITE_DATAS 					= 'GET_SITE_DATAS';
export const GET_SITE_DATAS_SUCCESS 			= 'GET_SITE_DATAS_SUCCESS';
export const GET_SITE_DATAS_FAILURE 			= 'GET_SITE_DATAS_FAILURE';

// for general infos
export const GET_CURRENCY_ATTRS 				= 'GET_CURRENCY_ATTRS';
export const GET_CURRENCY_ATTRS_SUCCESS 		= 'GET_CURRENCY_ATTRS_SUCCESS';
export const GET_STRINGS_SUCCESS 				= 'GET_STRINGS_SUCCESS';

// for user
export const GET_USER_SUCCESS 					= 'GET_USER_SUCCESS';
export const LOGOUT_SUCCESS 					= 'LOGOUT_SUCCESS';
export const EDIT_PROFILE_CLOSE_POPUP 			= 'EDIT_PROFILE_CLOSE_POPUP';
export const EDIT_PROFILE_SUBMITTING 			= 'EDIT_PROFILE_SUBMITTING';
export const EDIT_PROFILE_SUCCESS 				= 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE 				= 'EDIT_PROFILE_FAILURE';
// user notifications
export const GET_NOTIFICATIONS 					= 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_SUCCESS 			= 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILURE 			= 'GET_NOTIFICATIONS_FAILURE';
export const REFRESH_NOTIFICATIONS 				= 'REFRESH_NOTIFICATIONS';
export const LMORE_NOTIFICATIONS 				= 'LMORE_NOTIFICATIONS';
export const LMORE_NOTIFICATIONS_SUCCESS 		= 'LMORE_NOTIFICATIONS_SUCCESS';
export const LMORE_NOTIFICATIONS_FAILURE 		= 'LMORE_NOTIFICATIONS_FAILURE';
// user bookings
export const GET_USER_BOOKINGS 					= 'GET_USER_BOOKINGS';
export const GET_USER_BOOKINGS_SUCCESS 			= 'GET_USER_BOOKINGS_SUCCESS';
export const GET_USER_BOOKINGS_FAILURE 			= 'GET_USER_BOOKINGS_FAILURE';

export const LMORE_USER_BOOKINGS 				= 'LMORE_USER_BOOKINGS';
export const LMORE_USER_BOOKINGS_SUCCESS 		= 'LMORE_USER_BOOKINGS_SUCCESS';
export const LMORE_USER_BOOKINGS_FAILURE 		= 'LMORE_USER_BOOKINGS_FAILURE';

// for listing screen
export const GET_LISTING 						= 'GET_LISTING';
export const GET_LISTING_SUCCESS 				= 'GET_LISTING_SUCCESS';
export const GET_LISTING_ERROR 					= 'GET_LISTING_ERROR';

// for listing comment
export const REVIEW_SUBMIT 						= 'REVIEW_SUBMIT';
export const REVIEW_SUBMIT_SUCCESS 				= 'REVIEW_SUBMIT_SUCCESS';
export const REVIEW_SUBMIT_FAILURE 				= 'REVIEW_SUBMIT_FAILURE';
export const REVIEW_SUBMIT_CLOSE_POPUP 			= 'REVIEW_SUBMIT_CLOSE_POPUP';

// for listing comment
export const CLAIM_SUBMIT 						= 'CLAIM_SUBMIT';
export const CLAIM_SUBMIT_SUCCESS 				= 'CLAIM_SUBMIT_SUCCESS';

export const BOOKMARK_LISTING_SUCCESS 			= 'BOOKMARK_LISTING_SUCCESS';


// for booking
export const CKINOUT_SELECTED 					= 'CKINOUT_SELECTED';
export const PROCESS_TO_CHECKOUT 				= 'PROCESS_TO_CHECKOUT'; // pas data to checkout screen
export const CKINOUT_SUBMITTING 				= 'CKINOUT_SUBMITTING'; 
export const CHECKOUT_SUBMIT_SUCCESS 			= 'CHECKOUT_SUBMIT_SUCCESS'; 
export const CHECKOUT_SUBMIT_FAILURE 			= 'CHECKOUT_SUBMIT_FAILURE'; 
export const CHECKOUT_EXIT 						= 'CHECKOUT_EXIT'; 
export const BOOKING_STATUS 					= 'BOOKING_STATUS'; 
// single booking
export const BOOKING_CANCEL 					= 'BOOKING_CANCEL'; 
export const BOOKING_CANCEL_SUCCESS 			= 'BOOKING_CANCEL_SUCCESS'; 
export const BOOKING_CANCEL_FAILURE 			= 'BOOKING_CANCEL_FAILURE'; 

// for filter
export const FILTER_BY_CAT 						= 'FILTER_BY_CAT';
export const FILTER_BY_LOC 						= 'FILTER_BY_LOC';
export const FILTER_BY_TAG 						= 'FILTER_BY_TAG';
export const FILTER_BY_FEA 						= 'FILTER_BY_FEA';
export const FILTER_NEAR_BY 					= 'FILTER_NEAR_BY';
export const FILTER_RESET 						= 'FILTER_RESET';
export const APPLY_FILTERS 						= 'APPLY_FILTERS';



// for archive

export const GET_LISTINGS_START 				= 'GET_LISTINGS_START';
export const GET_LISTINGS_SUCCESS 				= 'GET_LISTINGS_SUCCESS';
export const GET_LISTINGS_FAILURE 				= 'GET_LISTINGS_FAILURE';

export const LMORE_LISTINGS_START 				= 'LMORE_LISTINGS_START';
export const LMORE_LISTINGS_SUCCESS 			= 'LMORE_LISTINGS_SUCCESS';
export const LMORE_LISTINGS_FAILURE 			= 'LMORE_LISTINGS_FAILURE';

// chat
export const GET_CONTACTS 						= 'GET_CONTACTS';
export const GET_CONTACTS_SUCCESS 				= 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAILURE 				= 'GET_CONTACTS_FAILURE';

export const GET_REPLIES 						= 'GET_REPLIES';
export const GET_REPLIES_SUCCESS 				= 'GET_REPLIES_SUCCESS';
export const GET_REPLIES_FAILURE 				= 'GET_REPLIES_FAILURE';

export const GET_TOP_REPLIES 					= 'GET_TOP_REPLIES';
export const GET_TOP_REPLIES_SUCCESS 			= 'GET_TOP_REPLIES_SUCCESS';



export const POST_REPLY_SUCCESS 				= 'POST_REPLY_SUCCESS';
export const CLEAR_REPLIES 						= 'CLEAR_REPLIES';








